name: moonai
channels:
  - pytorch-lts
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cudatoolkit=10.2.89
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.2.2
  - python=3.8.13
  - pytorch=1.8.2
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipykernel==6.17.0
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==7.4.4
    - jupyter-console==6.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclassic==0.4.7
    - nbclient==0.7.0
    - nbconvert==7.2.3
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.0
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.31
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.1
    - python-dateutil==2.8.2
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - send2trash==1.8.0
    - sklearn==0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.0
    - terminado==0.17.0
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - widgetsnbextension==4.0.3
    - zipp==3.10.0

